### ISSUE TITLE
API (rdbms-get-history "Gai4549xpewYUK3CebAS2TFczp4boJG21B") not returning correct no of transactions and amount

### ISSUE THREAD

**Issue by ghost** [glv2/peercoin-blockchain-parser#2]
@glv2 I am using (rdbms-get-history "some Address of Different blockchain") to get history of the address. But i am not getting correct no of transactions and amount.
When i hit this API with some address "Gai4549xpewYUK3CebAS2TFczp4boJG21B" it returned 2 transactions but when checked in daemon server, no of transactions was 3, also the amount was different.
Please help in this regard, 
Thanks

**Comment by glv2** [comment]
Are there still missing transactions in the history after calling ```(rdbms-update-database-from-rpc)```  or ```(rdbms-update-database-from-blockchain)``` ?

**Comment by ghost** [comment]
@glv2 Yes, I have updated the database with (rdbms-update-database-from-rpc), it has synced all blocks of chain, but still i don't get correct no of transactions and amount in transactions. May be this is merging some transactions, Please help for this issue,

**Comment by glv2** [comment]
Is the missing transaction related to minting?
Because for minting transactions, the ```rdbms-get-history``` function returns the merged input and output (so that you only see the block reward).
If that is the case, the sum of all the transaction amounts should still give the right final balance.
You could also check if the ```rdbms-get-balance``` function returns the right result.

**Comment by ghost** [comment]
We are working on "https://github.com/MatthewLM/PeercoinAbeExplorer" to get details of any given address
